var lyrics = [
  ["Put your hand on your heart and ask what your dream was, What it really was.","gaseume soneul eontgo malhaebwa nae kkumeun mwoyeotji?\neo jinjja mwoyeotji","가슴에 손을 얹고 말해봐 내 꿈은 뭐였지?\n어 진짜 뭐였지","O!RUL8,2?","https://open.spotify.com/track/3Jqecns7MfqxumyVCyXgJA?si=RIwxSK-uRrm2VlD2xqKMkA","https://www.youtube.com/watch?v=5BwrWn8ST-8","https://colorcodedlyrics.com/2014/08/bts-bangtansonyeondan-intro-o-rul8-2"  ],
  ["Never be late to do what you wanna do right now","","","O!RUL8,2?","https://open.spotify.com/track/3Jqecns7MfqxumyVCyXgJA?si=RIwxSK-uRrm2VlD2xqKMkA","https://www.youtube.com/watch?v=5BwrWn8ST-8","https://colorcodedlyrics.com/2014/08/bts-bangtansonyeondan-intro-o-rul8-2"  ],
  ["Take chances and never regret, never","","","O!RUL8,2?","https://open.spotify.com/track/3Jqecns7MfqxumyVCyXgJA?si=RIwxSK-uRrm2VlD2xqKMkA","https://www.youtube.com/watch?v=5BwrWn8ST-8","https://colorcodedlyrics.com/2014/08/bts-bangtansonyeondan-intro-o-rul8-2"  ],
  ["Nothing lasts forever","","","O!RUL8,2?","https://open.spotify.com/track/3Jqecns7MfqxumyVCyXgJA?si=RIwxSK-uRrm2VlD2xqKMkA","https://www.youtube.com/watch?v=5BwrWn8ST-8","https://colorcodedlyrics.com/2014/08/bts-bangtansonyeondan-intro-o-rul8-2"  ],
  ["Who are you living for?","neon daeche nugul wihae sanya","넌 대체 누굴 위해 사냐","O!RUL8,2?","https://open.spotify.com/track/3Jqecns7MfqxumyVCyXgJA?si=RIwxSK-uRrm2VlD2xqKMkA","https://www.youtube.com/watch?v=5BwrWn8ST-8","https://colorcodedlyrics.com/2014/08/bts-bangtansonyeondan-intro-o-rul8-2"  ],
  ["The world is a complex","","","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["But I found myself","","","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["I’m confused too, which one’s the real me?","nado hetgallyeo daeche eotteon ge jinjja nanji","나도 헷갈려 대체 어떤 게 진짜 난지","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["You’re my beginning and my end","neon naege shijagija gyeolmal jachenikka","넌 내게 시작이자 결말 자체니까","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["You’re the answer","e daehan answer","에 대한 answer","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["Maybe I’m your truth and your lie","eojjeomyeon naneun neoye jinshirija geojishilji molla","어쩌면 나는 너의 진실이자 거짓일지 몰라","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["Maybe I’m your love and hate","eojjeomyeon dangshine sarangija jeungo","어쩌면 당신의 사랑이자 증오","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["Maybe I’m your enemy and friend","eojjeomyeon naneun neoye wonsuija beot","어쩌면 나는 너의 원수이자 벗","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["I always make an effort to be the best for you","eonjena dangshine choegoga doegi wihae noryeogeul hae","언제나 당신의 최고가 되기 위해 노력을 해","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["I’m your star, I shine as if nothing’s wrong","geudaemane byeol amu il eopshi bitnamyeonseodo","그대만의 별 아무 일 없이 빛나면서도","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["Just going wherever my heart goes","geujeo mam ganeun daero","그저 맘 가는 대로","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["Love makes a person go crazy","sarangeun sarameul michige hae","사랑은 사람을 미치게 해","Outro: Her","https://open.spotify.com/track/3l8yQMdniG6Os8gUBNXV57?si=JtIrQiceTQKwwz9UZo8WtQ","","https://colorcodedlyrics.com/2017/09/bts-bangtansonyeondan-outro"  ],
  ["I bet it got my haters hella sick","","","MIC Drop (Steve Aoki Remix)","https://open.spotify.com/track/75scDPqGs75FotglJSoOI2?si=lfrx32LiRAywjd5reAD_iA","https://youtu.be/kTlv5_Bs8aw","https://colorcodedlyrics.com/2017/11/bts-bangtansonyeondan-mic-drop-steve-aoki-remix"  ],
  ["Bad odors with good scents are against the rules","joeun hyanggie akchwin banchik","좋은 향기에 악췬 반칙","MIC Drop (Steve Aoki Remix)","https://open.spotify.com/track/75scDPqGs75FotglJSoOI2?si=lfrx32LiRAywjd5reAD_iA","https://youtu.be/kTlv5_Bs8aw","https://colorcodedlyrics.com/2017/11/bts-bangtansonyeondan-mic-drop-steve-aoki-remix"  ],
  ["Somebody stop me","","","MIC Drop (Steve Aoki Remix)","https://open.spotify.com/track/75scDPqGs75FotglJSoOI2?si=lfrx32LiRAywjd5reAD_iA","https://youtu.be/kTlv5_Bs8aw","https://colorcodedlyrics.com/2017/11/bts-bangtansonyeondan-mic-drop-steve-aoki-remix"  ],
  ["Nothing more left to say, don’t even apologize","hal maldo eopseo sagwado haji ma","할 말도 없어 사과도 하지 마","MIC Drop (Steve Aoki Remix)","https://open.spotify.com/track/75scDPqGs75FotglJSoOI2?si=lfrx32LiRAywjd5reAD_iA","https://youtu.be/kTlv5_Bs8aw","https://colorcodedlyrics.com/2017/11/bts-bangtansonyeondan-mic-drop-steve-aoki-remix"  ],
  ["I grew a flower that couldn’t be blossomed","piul su eomneun kkocheul kiweosseo","피울 수 없는 꽃을 키웠어","FAKE LOVE","https://open.spotify.com/track/3aW0ds4A4tSQDIp75FqWTo?si=nyEBnYhVSHytRaPO4S1kCQ","https://www.youtube.com/watch?v=7C2z4GqqS5E","https://colorcodedlyrics.com/2018/05/bts-bangtansonyeondan-fake-love"  ],
  ["Cause I was always just me","naneun hangsang nayeotgie","나는 항상 나였기에","IDOL (Feat. Nicki Minaj)","https://open.spotify.com/track/03iCbZaM4OkRR4We6wIzvx?si=KbBXvkolRIq2tp0iju-r6w","https://www.youtube.com/watch?v=K1scjjbfNsk","https://colorcodedlyrics.com/2018/08/bts-bangtansonyeondan-idol-feat-nicki-minaj"  ],
  ["You can’t stop me lovin’ myself","","","IDOL (Feat. Nicki Minaj)","https://open.spotify.com/track/03iCbZaM4OkRR4We6wIzvx?si=KbBXvkolRIq2tp0iju-r6w","https://www.youtube.com/watch?v=K1scjjbfNsk","https://colorcodedlyrics.com/2018/08/bts-bangtansonyeondan-idol-feat-nicki-minaj"  ],
  ["There are hundreds of me’s inside of me","nae soganen myeot ship myeot baengmyeonge naega isseo","내 속안엔 몇 십 몇 백명의 내가 있어","IDOL (Feat. Nicki Minaj)","https://open.spotify.com/track/03iCbZaM4OkRR4We6wIzvx?si=KbBXvkolRIq2tp0iju-r6w","https://www.youtube.com/watch?v=K1scjjbfNsk","https://colorcodedlyrics.com/2018/08/bts-bangtansonyeondan-idol-feat-nicki-minaj"  ],
  ["I’m facing a new me again today","oneul tto dareun nal majihae","오늘 또 다른 날 맞이해","IDOL (Feat. Nicki Minaj)","https://open.spotify.com/track/03iCbZaM4OkRR4We6wIzvx?si=KbBXvkolRIq2tp0iju-r6w","https://www.youtube.com/watch?v=K1scjjbfNsk","https://colorcodedlyrics.com/2018/08/bts-bangtansonyeondan-idol-feat-nicki-minaj"  ],
  ["It’s okay, I’m happy in this moment","It’s okay, nan i sungan haengbokhae"," It’s okay, 난 이 순간 행복해","IDOL (Feat. Nicki Minaj)","https://open.spotify.com/track/03iCbZaM4OkRR4We6wIzvx?si=KbBXvkolRIq2tp0iju-r6w","https://www.youtube.com/watch?v=K1scjjbfNsk","https://colorcodedlyrics.com/2018/08/bts-bangtansonyeondan-idol-feat-nicki-minaj"  ],
  ["My blood, sweat and tears","nae pi ttam nunmul","내 피 땀 눈물"," Blood Sweat & Tears (피 땀 눈물)","https://open.spotify.com/track/5RGf8qn1TBWVplLyyKUsuV?si=7IC5UX9iRFOcvX-kOuPnbw","https://www.youtube.com/watch?v=hmE9f-TEutc","https://colorcodedlyrics.com/2016/10/bts-blood-sweat-tears-pi-ttam-nunmul"  ],
  ["I wanna be addicted to your prison","neoran gamoge jungdokdwae gipi","너란 감옥에 중독돼 깊이"," Blood Sweat & Tears (피 땀 눈물)","https://open.spotify.com/track/5RGf8qn1TBWVplLyyKUsuV?si=7IC5UX9iRFOcvX-kOuPnbw","https://www.youtube.com/watch?v=hmE9f-TEutc","https://colorcodedlyrics.com/2016/10/bts-blood-sweat-tears-pi-ttam-nunmul"  ],
  ["My heart makes time run","maeumeun shiganeul dallyeogane","마음은 시간을 달려가네","Spring Day (봄날)","https://open.spotify.com/track/0WNGsQ1oAuHzNTk8jivBKW?si=ZcD8y4ZpSnqTb54oZiHQxg","https://www.youtube.com/watch?v=xEeFrLSkMm8","https://colorcodedlyrics.com/2017/02/bts-bangtansonyeondan-spring-day-bomnal"  ],
  ["There hasn’t been a day that I have forgotten you","dan harudo neoreul ijeun jeogi eopseotji nan","단 하루도 너를 잊은 적이 없었지 난","Spring Day (봄날)","https://open.spotify.com/track/0WNGsQ1oAuHzNTk8jivBKW?si=ZcD8y4ZpSnqTb54oZiHQxg","https://www.youtube.com/watch?v=xEeFrLSkMm8","https://colorcodedlyrics.com/2017/02/bts-bangtansonyeondan-spring-day-bomnal"  ],
  ["Hey you, what’s your dream?","yamma ni ggumeun mwoni","얌마 니 꿈은 뭐니","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Is that all your dream is?","ni ggumeun gyeou geugeoni","니 꿈은 겨우 그거니","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["What is the you that you’ve dreamed of?","niga ggumkkwo-on ni moseubi mwoyeo","니가 꿈꿔온 니 모습이 뭐여","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Who do you see in the mirror?","jigeum ni geoul sogen nuga boyeo","지금 니 거울 속엔 누가 보여","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Go on your path","neoui gireul garago","너의 길을 가라고","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Even if you live for a day, Do something","dan harureul sarado, mworado harago","단 하루를 살아도, 뭐라도 하라고","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Why aren’t you saying anything?","wae mal mothago isseo? ","왜 말 못하고 있어?","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Ask yourself if you’ve ever worked hard for anything"," jasinege mureobwa eon je niga yeolsimhi noryeokhaetnyago","자신에게 물어봐 언 제 니가 열심히 노력했냐고","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["dreams are a special pardon","ggumeul teukbyeolsamyeon","꿈을 특별사면","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Become the main subject of your life that has always been suppressed","eogabman batdeon insaeng ni sarmui jueoga doe-eobwa","억압만 받던 인생 니 삶의 주어가 되어봐","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Dream a dream now","ggumeul ggumeul ggumeul ggwobwa da","꿈을 꿈을 꿈을 꿔봐 다","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["To all the youngsters without dreams.","","","No More Dream","https://open.spotify.com/track/4frlkLwlnm58ejpNwWjxyl?si=d61MWlg2QDmCOgZECCAPhQ","https://www.youtube.com/watch?v=rBG5L7UsUxA","https://colorcodedlyrics.com/2013/06/bts-bangtansonyeondan-no-more-dream"  ],
  ["Everyone lives the same life","ildeungeul gangyo","일등을 강요","N.O","https://open.spotify.com/track/1hehPTlSVIhHEvCkVoe4HX?si=oFgyipDiSMGdg_Q59lQBFg","https://www.youtube.com/watch?v=mmgxPLLLyVo","https://colorcodedlyrics.com/2013/09/bts-bangtansonyeondan-n-o"  ],
  ["One live in between dreams and reality","hyeonsil saiui ijunggancheop","현실 사이의 이중간첩","N.O","https://open.spotify.com/track/1hehPTlSVIhHEvCkVoe4HX?si=oFgyipDiSMGdg_Q59lQBFg","https://www.youtube.com/watch?v=mmgxPLLLyVo","https://colorcodedlyrics.com/2013/09/bts-bangtansonyeondan-n-o"  ],
  ["Don’t be trapped in someone else’s dream","deoneun namui kkume gatyeo salji ma","더는 남의 꿈에 갇혀 살지 마","N.O","https://open.spotify.com/track/1hehPTlSVIhHEvCkVoe4HX?si=oFgyipDiSMGdg_Q59lQBFg","https://www.youtube.com/watch?v=mmgxPLLLyVo","https://colorcodedlyrics.com/2013/09/bts-bangtansonyeondan-n-o"  ],
  ["My unhappiness is past its limit","nae bulhaengeun handochogwaji","내 불행은 한도초과지","N.O","https://open.spotify.com/track/1hehPTlSVIhHEvCkVoe4HX?si=oFgyipDiSMGdg_Q59lQBFg","https://www.youtube.com/watch?v=mmgxPLLLyVo","https://colorcodedlyrics.com/2013/09/bts-bangtansonyeondan-n-o"  ],
  ["Living the life of a puppet, Who will take responsibility?","ttokgateun kkokdugaksi insaeng, dodaeche nuga chaegimjyeojwo?","똑같은 꼭두각시 인생, 도대체 누가 책임져줘?","N.O","https://open.spotify.com/track/1hehPTlSVIhHEvCkVoe4HX?si=oFgyipDiSMGdg_Q59lQBFg","https://www.youtube.com/watch?v=mmgxPLLLyVo","https://colorcodedlyrics.com/2013/09/bts-bangtansonyeondan-n-o"  ],
  ["I worked all night, every day, While you were playing in the club ","bamsae ilhaettji everyday, niga keulleobeseo nol ttae yeah","밤새 일했지 everyday, 니가 클럽에서 놀 때 yeah","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["cuz I’m sick with hope haha","uz nan huimangi jjeoreo haha","cuz 난 희망이 쩔어 haha","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["I gotta make it, I gotta make it","","","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["Reject rejection","geobuneun geobuhae","거부는 거부해","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["Why are they killing us before we can even try","wae haebogido jeone jugyeo gyaenen","왜 해보기도 전에 죽여 걔넨 ","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["Don’t ever give up, you know you not lonely","jeoldae ma pogi you know you not lonely","절대 마 포기 you know you not lonely","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["Our dawn is prettier than the day","neowa nae saebyeogeun natboda yeppeo","너와 내 새벽은 낮보다 예뻐","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["So can I get a little bit of hope? ","","","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["Every day is about the hustle life","maeiri hustle life","매일이 hustle life","Dope","https://open.spotify.com/track/4TiKZrN7gtc62SUiufpFCM?si=E-5h9850RGqorSlJWFSzqg","https://www.youtube.com/watch?v=H8lYMWZD5P8","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-sick-jjeoleo"  ],
  ["But my ambition grew too big","but nae yamangi neomu keojyeosseo","But 내 야망이 너무 커졌어","Moving On","https://open.spotify.com/track/4nWJ7msY5lWNK74UKbAVw5?si=WaW9hEoBSVemxDv6heVF9Q","","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-isa-move"  ],
  ["Good things were always other people’s things","joheun geon eonjena da namdeurui moksieossgo","좋은 건 언제나 다 남들의 몫이었고","Moving On","https://open.spotify.com/track/4nWJ7msY5lWNK74UKbAVw5?si=WaW9hEoBSVemxDv6heVF9Q","","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-isa-move"  ],
  ["Let’s not forget those things but put them away","haessdeon kkujilhan gieok ijjin malgo ttak neoheodujago","했던 꾸질한 기억 잊진 말고 딱 넣어두자고","Moving On","https://open.spotify.com/track/4nWJ7msY5lWNK74UKbAVw5?si=WaW9hEoBSVemxDv6heVF9Q","","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-isa-move"  ],
  ["We cried a lot and laughed a lot but it was so beautiful","ulgido usgido manhi haessjiman modu kkwaena areumdawosseo","울기도 웃기도 많이 했지만 모두 꽤나 아름다웠어","Moving On","https://open.spotify.com/track/4nWJ7msY5lWNK74UKbAVw5?si=WaW9hEoBSVemxDv6heVF9Q","","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-isa-move"  ],
  ["A lot of things happened, there were many memories","manheun ildeuri issgo manheun chueogui gieogi","많은 일들이 있고 많은 추억의 기억이","Moving On","https://open.spotify.com/track/4nWJ7msY5lWNK74UKbAVw5?si=WaW9hEoBSVemxDv6heVF9Q","","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-isa-move"  ],
  ["I lived with my pride","nae jajonsimeun bojeunggeum","내 자존심은 보증금","Moving On","https://open.spotify.com/track/4nWJ7msY5lWNK74UKbAVw5?si=WaW9hEoBSVemxDv6heVF9Q","","https://colorcodedlyrics.com/2015/06/bts-bangtansonyeondan-isa-move"  ]
]

var pics=[]
const randIndex = Math.floor(Math.random() * lyrics.length)
console.log(randIndex);

const ranLyric = lyrics[randIndex];
console.log(ranLyric);

// var body = document.getElementsByTagName('body');
// document.body.style.background = 'url(img/pic/1.png) no-repeat center center fixed';
// document.body.style.backgroundSize = 'cover';

document.getElementById('engLyric').innerHTML = ranLyric[0];
document.getElementById('romLyric').innerHTML = ranLyric[1];
document.getElementById('korLyric').innerHTML = ranLyric[2];
document.getElementById('songName').innerHTML = "- <a href= '" +ranLyric[6]+"' target='_blank'>"+ranLyric[3]+"</a>";
document.getElementById('spotify').innerHTML = "<a href= '" +ranLyric[4]+"' target='_blank'><img class='spotify' src='img/logo/spotify.png' alt='Spotify'></a>";

if (ranLyric[5]) {
document.getElementById('youtube').innerHTML = "<a href= '" +ranLyric[5]+"' target='_blank'><img class='youtube' src='img/logo/yt.png' alt='Youtube'></a>";
}

